#!/usr/bin/env sh
set -eu

[ "$#" -ne 0 ] && { echo "No arguments expected" >&2; exit 1; }

./download

rm -rf NVIDIA-Linux-x86_64-470.256.02
sh NVIDIA-Linux-x86_64-470.256.02.run --extract-only

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
apply_patch() {
    patch -Np1 -i "$SCRIPTPATH/$1"
}

cd NVIDIA-Linux-x86_64-470.256.02/kernel
apply_patch patches/0037-import-pfn_valid-w-o-GPL-rcu_read_lock-unlock-from-v.patch
apply_patch patches/0043-backport-follow_pfn-changes-from-550.90.07.patch
apply_patch patches/0045-let-the-virt_addr_valid-macro-use-nv_pfn_valid-on-pp.patch
apply_patch patches/0046-backport-nv_get_kern_phys_address-changes-from-555.4.patch
apply_patch patches/0047-backport-drm_output_poll_changed-changes-from-535.21.patch
apply_patch patches/0048-backport-cmd_symlink-changes-from-550.142.patch
apply_patch patches/0049-backport-uvm-warning-fixes-from-510.39.01.patch
apply_patch patches/0049-backport-warning-fixes-from-525.53.patch
apply_patch patches/0050-backport-uvm-warning-fixes-from-535.146.02.patch
apply_patch patches/0051-backport-warning-fixes-from-535.216.01.patch
apply_patch patches/0052-backport-uvm-warning-fixes-from-560.28.03.patch
apply_patch patches/0053-fix-more-warnings.patch
apply_patch patches/0054-backport-warning-fixes-from-575.51.02.patch
apply_patch patches/0054-fix-more-uvm-warnings.patch
apply_patch patches/0055-backport-file_operations_fop_unsigned_offset_present.patch
apply_patch patches/0056-backport-LD_SCRIPT-changes-from-535.230.02.patch
apply_patch patches/0057-backport-uvm-fixes-from-535.230.02.patch
apply_patch patches/0058-backport-warning-fixes-from-565.57.01.patch
apply_patch patches/0059-backport-uvm-warning-fixes-from-550.90.07.patch
apply_patch patches/0060-backport-build_cflags-changes-from-525.85.05.patch
apply_patch patches/0061-backport-drm_gem_object_vmap_has_map_arg-changes-fro.patch
apply_patch patches/0064-backport-drm_driver_has_date-from-570.124.04.patch
apply_patch patches/0065-backport-ccflags-y-changes-from-570.153.02.patch
apply_patch patches/0066-backport-nv_timer_delete_sync-changes-from-570.153.0.patch
apply_patch patches/0067-backport-drm_connector_helper_funcs_mode_valid_has_c.patch
apply_patch patches/0074-backport-drm_fb_create_takes_format_info-changes-fro.patch
apply_patch patches/gcc-14.patch
apply_patch patches/nvidia-470xx-fix-linux-6.15.patch
apply_patch patches/nvidia-470xx-fix-linux-6.19-part1.patch
apply_patch patches/nvidia-470xx-fix-linux-6.19-part2.patch
apply_patch patches/nvidia-470xx-MODULE_DESCRIPTION.patch
apply_patch patches/nvidia-UBSAN.patch
apply_patch patches/enable-drm-modeset-by-default.patch
